version: "3.1"

services:
  db:
    build: ./packages/database
    restart: unless-stopped
    ports:
      - ${PGPORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pms-alpha-volume:/var/lib/postgresql/data

volumes:
  pms-alpha-volume:
