import React from "react";
import Head from "next/head";

import NewDiagnosisForm from "components/diagnosis/new";
import SearchDiagnosis from "components/diagnosis/search";
import ImportDiagnosis from "components/diagnosis/import";

import type { NextPage } from "next";

const Diagnosis: NextPage = () => {
  return (
    <>
      <Head>
        <title>PMS-alpha </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchDiagnosis />

      <NewDiagnosisForm />

      <ImportDiagnosis />
    </>
  );
};

export default Diagnosis;
