import type { NextPage } from "next";
import Head from "next/head";
import { Flex, Text } from "@chakra-ui/react";
import React from "react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PMS-alpha </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex h="100vh" bgColor="gray.200" align="center" justify="center" m={5}>
        <Text fontSize="2xl" fontWeight="semibold">
          Welcome to PMS infinity.3V
        </Text>
      </Flex>
    </div>
  );
};

export default Home;
