import type { NextPage } from "next";
import Head from "next/head";
import { Flex, Text } from "@chakra-ui/react";
import React from "react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PMS-alpha </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex grow={1} align="center" justify="center">
        <Text fontSize="2xl" fontWeight="semibold">
          Welcome to PMS
        </Text>
      </Flex>
    </>
  );
};

export default Home;
